# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05greet\"/\n\x0cHelloRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"-\n\nRegistrate\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x81\x01\n\x08Greeting\x12\x38\n\tHelloEcho\x12\x13.greet.HelloRequest\x1a\x14.greet.HelloResponse\"\x00\x12;\n\x0eRegistrateUser\x12\x11.greet.Registrate\x1a\x14.greet.HelloResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=22
  _HELLOREQUEST._serialized_end=69
  _REGISTRATE._serialized_start=71
  _REGISTRATE._serialized_end=116
  _HELLORESPONSE._serialized_start=118
  _HELLORESPONSE._serialized_end=150
  _GREETING._serialized_start=153
  _GREETING._serialized_end=282
# @@protoc_insertion_point(module_scope)
